# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: rollup 2.0.0 npm & build test

on:
- push
- pull_request

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
        - ubuntu-latest
        - windows-latest
        - macos-latest
        node-version:
        - 16.x

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        # (with no npm cache)
    - run: yarn
    - run: yarn add --dev rollup@2.0.0
    - run: yarn why rollup # should show use of rollup@2.0.0
    - run: npm test
    - run: yarn test-build # test if generated dist will work with rollup@2.0.0
